name: AFL CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Install OpenSSL 1.0.2
      run: sudo apt-get install libssl1.0-dev -y
    - uses: actions/checkout@v2
    - name: install afl
      run: git clone https://github.com/google/AFL -b v2.56b; cd AFL; make; sudo make install
    - name: configure libdopenssl
      run: export CC=/usr/local/bin/afl-gcc; rm -rf build; mkdir build; cd build; cmake ..
    - name: build fuzzied libdopenssl
      run: cd build; make
    - name: install fuzzied libdopenssl
      run: cd build; sudo make install
    - name: build fuzzied sample
      run: afl-gcc src/sample.c -o sample -ldopenssl -lcrypto
    - name: create afl setup
      run: mkdir -p afl/in; mkdir -p afl/out; sh -c 'cat /dev/urandom |tr -dc A-Z9|head -c${1:-81} >> afl/1'; sh -c 'cat /dev/urandom |tr -dc A-Z9|head -c${1:-81} >> afl/2'; sh -c 'cat /dev/urandom |tr -dc A-Z9|head -c${1:-81} >> afl/3';
    - name: modify core_pattern kernel parameter
      run: sudo sh -c 'echo core >/proc/sys/kernel/core_pattern'
    - name: run afl-fuzz
      run: afl-fuzz -i afl/in -o afl/out2 ./sample
