name: C/C++ CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Install OpenSSL 1.0.2
      run: sudo apt-get install libssl1.0-dev -y
    - uses: actions/checkout@v2
    - name: configure
      run: rm -rf build; mkdir build; cd build; cmake ..
    - name: make
      run: cd build; make
